package com.engin.focab.jpa;

//********************************************
//Generated by http://www.jsonschema2pojo.org/
//********************************************


import java.util.List;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class QuoDBResultHeader {

@SerializedName("QuoDBResultHeader")
@Expose
private List<QuoDBResult> quoDBResults = null;

public List<QuoDBResult> getQuoDBResults() {
	return quoDBResults;
}

public void setQuoDBResults(List<QuoDBResult> quoDBResults) {
	this.quoDBResults = quoDBResults;
}



}